import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Provider from "./Provider";
const OutfitSans = Outfit({
  variable: "--font-Outfit-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      
      <body className={`${OutfitSans.variable} antialiased`}>
        <Header />
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
}
